genre_mapping = {
    'chicago rap': 'rap',
    'canadian pop': 'pop',
    'dance pop': 'pop',
    'barbadian pop': 'pop',
    'pop': 'pop',
    'art pop': 'pop',
    'british soul': 'soul',
    'tropical house': 'house',
    'folk-pop': 'pop',
    'metropopolis': 'pop',
    'hip pop': 'hip-hop',
    'boy band': 'pop',
    'big room': 'edm',
    'canadian contemporary r&b': 'r&b',
    'neo mellow': 'pop',
    'indie pop': 'pop',
    'brostep': 'edm',
    'moroccan pop': 'pop',
    'escape room': 'pop',
    'hip hop': 'hip-hop',
    'atl hip hop': 'hip-hop',
    'electropop': 'pop',
    'canadian hip hop': 'hip-hop',
    'australian dance': 'edm',
    'candy pop': 'pop',
    'permanent wave': 'pop',
    'latin': 'pop',
    'colombian pop': 'pop',
    'electro house': 'edm',
    'complextro': 'edm',
    'celtic rock': 'rock',
    'canadian latin': 'latin',
    'electro': 'edm',
    'hollywood': 'pop',
    'acoustic pop': 'pop',
    'edm': 'edm',
    'detroit hip hop': 'hip-hop',
    'french indie pop': 'pop',
    'house': 'house',
    'downtempo': 'electronic',
    'australian hip hop': 'hip-hop',
    'australian pop': 'pop',
    'danish pop': 'pop',
    'alaska indie': 'indie',
    'baroque pop': 'pop',
    'electronic trap': 'edm',
    'contemporary country': 'country',
    'alternative r&b': 'r&b',
    'belgian edm': 'edm',
    'irish singer-songwriter': 'singer-songwriter'
}